export enum bgColors {
    A_ = '',
    B = '#FAAFA8',
    C = '#F39F76',
    D = '#FFF8B8',
    F = '#E2F6D3',
    G = '#B4DDD3',
    H = '#D4E4ED',
    I = '#AECCDC',
    J = '#D3BFDB',
    K = '#F6E2DD',
    L = '#E9E3D4',

    // B= '#77172e',
    // C = '#692b17',
    // D = '#7c4a03',
    // F = '#264d3b',
    // G = '#0c625d',
    // H = '#256377',
    // I = '#284255',
    // J = '#472e5b',
    // K = '#6c394f',
    // L= '#4b443a',
}

export enum bgImages {
    i0 = '',
    i1 = '/assets/images/backgrounds/Light/redLight.svg',
    i2 = '/assets/images/backgrounds/Light/orangeLight.svg',
    i3 = '/assets/images/backgrounds/Light/yellowLight.svg',
    i4 = '/assets/images/backgrounds/Light/greenLight.svg',
    i5 = '/assets/images/backgrounds/Light/tealLight.svg',
    i6 = '/assets/images/backgrounds/Light/aquaLight.svg',
    i7 = '/assets/images/backgrounds/Light/blueLight.svg',
    i8 = '/assets/images/backgrounds/Light/purpleLight.svg',
    i9 = '/assets/images/backgrounds/Light/pinkLight.svg',
    i95 = '/assets/images/backgrounds/Light/brownLight.svg',

    // i1 = '/assets/images/backgrounds/Dark/redDark.svg',
    // i2 = '/assets/images/backgrounds/Dark/orangeDark.svg',
    // i3 = '/assets/images/backgrounds/Dark/yellowDark.svg',
    // i4 = '/assets/images/backgrounds/Dark/greenDark.svg',
    // i5 = '/assets/images/backgrounds/Dark/tealDark.svg',
    // i6 = '/assets/images/backgrounds/Dark/aquaDark.svg',
    // i7 = '/assets/images/backgrounds/Dark/blueDark.svg',
    // i8 = '/assets/images/backgrounds/Dark/purpleDark.svg',
    // i9 = '/assets/images/backgrounds/Dark/pinkDark.svg',
    // i95 = '/assets/images/backgrounds/Dark/brownDark.svg',
}
