export enum bgColors {
    A_ = '',
    B = '#FAAFA8',
    C = '#F39F76',
    D = '#FFF8B8',
    F = '#E2F6D3',
    G = '#B4DDD3',
    H = '#D4E4ED',
    I = '#AECCDC',
    J = '#D3BFDB',
    K = '#F6E2DD',
    L = '#E9E3D4',

    // B= '#77172e',
    // C = '#692b17',
    // D = '#7c4a03',
    // F = '#264d3b',
    // G = '#0c625d',
    // H = '#256377',
    // I = '#284255',
    // J = '#472e5b',
    // K = '#6c394f',
    // L= '#4b443a',
}

export enum bgImages {
    i0 = '',
    i1 = '/assets/images/backgrounds/Light/i1.svg',
    i2 = '/assets/images/backgrounds/Light/i2.svg',
    i3 = '/assets/images/backgrounds/Light/i3.svg',
    i4 = '/assets/images/backgrounds/Light/i4.svg',
    i5 = '/assets/images/backgrounds/Light/i5.svg',
    i6 = '/assets/images/backgrounds/Light/i6.svg',
    i7 = '/assets/images/backgrounds/Light/i7.svg',
    i8 = '/assets/images/backgrounds/Light/i8.svg',
    i9 = '/assets/images/backgrounds/Light/i9.svg',
    i95 = '/assets/images/backgrounds/Light/i95.svg',

    // i1 = '/assets/images/backgrounds/Dark/i1.svg',
    // i2 = '/assets/images/backgrounds/Dark/i2.svg',
    // i3 = '/assets/images/backgrounds/Dark/i3.svg',
    // i4 = '/assets/images/backgrounds/Dark/i4.svg',
    // i5 = '/assets/images/backgrounds/Dark/i5.svg',
    // i6 = '/assets/images/backgrounds/Dark/i6.svg',
    // i7 = '/assets/images/backgrounds/Dark/i7.svg',
    // i8 = '/assets/images/backgrounds/Dark/i8.svg',
    // i9 = '/assets/images/backgrounds/Dark/i9.svg',
    // i95 = '/assets/images/backgrounds/Dark/i95.svg',
}


