export enum bgColors {
    A_ = '',
    B_red_light = '#FAAFA8',
    C_orange_light = '#F39F76',
    D_yellow_light = '#FFF8B8',
    F_green_light = '#E2F6D3',
    G_teal_light = '#B4DDD3',
    H_blue_light = '#D4E4ED',
    I_darkblue_light = '#AECCDC',
    J_purple_light = '#D3BFDB',
    K_pink_light = '#F6E2DD',
    L_brown_light = '#E9E3D4',

    // B_red_dark = '#77172e',
    // C_orange_dark = '#692b17',
    // D_yellow_dark = '#7c4a03',
    // F_green_dark = '#264d3b',
    // G_teal_dark = '#0c625d',
    // H_blue_dark = '#256377',
    // I_darkblue_dark = '#284255',
    // J_purple_dark = '#472e5b',
    // K_pink_dark = '#6c394f',
    // L_brown_dark = '#4b443a',
}

export enum bgImages {
    i0 = '',
    i1_light = '/assets/images/backgrounds/Light/redLight.svg',
    i2_light = '/assets/images/backgrounds/Light/orangeLight.svg',
    i3_light = '/assets/images/backgrounds/Light/yellowLight.svg',
    i4_light = '/assets/images/backgrounds/Light/greenLight.svg',
    i5_light = '/assets/images/backgrounds/Light/tealLight.svg',
    i6_light = '/assets/images/backgrounds/Light/aquaLight.svg',
    i7_light = '/assets/images/backgrounds/Light/blueLight.svg',
    i8_light = '/assets/images/backgrounds/Light/purpleLight.svg',
    i9_light = '/assets/images/backgrounds/Light/pinkLight.svg',
    i95_light = '/assets/images/backgrounds/Light/brownLight.svg',

    // i1_dark = '/assets/images/backgrounds/Dark/redDark.svg',
    // i2_dark = '/assets/images/backgrounds/Dark/orangeDark.svg',
    // i3_dark = '/assets/images/backgrounds/Dark/yellowDark.svg',
    // i4_dark = '/assets/images/backgrounds/Dark/greenDark.svg',
    // i5_dark = '/assets/images/backgrounds/Dark/tealDark.svg',
    // i6_dark = '/assets/images/backgrounds/Dark/aquaDark.svg',
    // i7_dark = '/assets/images/backgrounds/Dark/blueDark.svg',
    // i8_dark = '/assets/images/backgrounds/Dark/purpleDark.svg',
    // i9_dark = '/assets/images/backgrounds/Dark/pinkDark.svg',
    // i95_dark = '/assets/images/backgrounds/Dark/brownDark.svg',
}

